In [1]:
import cv2 as cv
import sys

### **DISPLAYING IMAGE**
---
---

#### `.imread()`: returns an image matrix

- img/path

- flag : 
    - IMREAD_COLOR loads the image in the BGR 8-bit format. This is the default that is used here.

    - IMREAD_UNCHANGED loads the image as is (including the alpha channel if present)

    - IMREAD_GRAYSCALE loads the image as an intensity one
---

#### `.imshow()`

- window name

- image matrix (returned by imread()) 
---

#### `.waitkey()`: return ASCII code of key pressed, if no key pressed then -1

- delay:
    
    - 0: wait until a key is pressed
    - \>0: wait for the specified amount of milliseconds
---

#### `.destroyAllWindows()`: destroys all cv2 windows
---

#### `.destroyWindow()`

- window name
---



        

In [4]:
img = cv.imread('download.jpg')

if img is None:
    sys.exit("Could not read image")

# print(img) # --> gives an image matrix

cv.imshow("FLOWER",img)

char = cv.waitKey(0)

print(chr(char)," pressed.")

cv.destroyWindow("FLOWER")

  pressed.


### **SAVING IMAGE**

---
---

#### `.imwrite()`: return True/False

- filename

- image matrix

- params : []

    - jpeg parameter:

        - cv.IMWRITE_JPEG_QUALITY (img quality): 0 - 100

        - cv.IMWRITE_JPEG_PROGRESSIVE: 0/1 [0-normal; 1-progressive]

        - cv.IMWRITE_JPEG_OPTIMIZE: 0/1 [0-no optimization; 1-optimization]

        - cv.IMWRITE_JPEG_RST_INTERVAL: error recovery, not used practically

        - cv.IMWRITE_JPEG_LUMA_QUALITY: 0-100 [ brightness ]

        - cv.IMWRITE_JPEG_CHROMA_QUALITY: 0-100 [ color quality ]
        
    - png parameter:

        - cv.IMWRITE_PNG_COMPRESSION: 0-9

        - cv.IMWRITE_PNG_STRATEGY (**cv.IMWRITE_PNG_STRATEGY_DEFAULT**; cv.IMWRITE_PNG_STRATEGY_FILTERED; cv.IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY;
        cv.IMWRITE_PNG_STRATEGY_RLE; cv.IMWRITE_PNG_STRATEGY_FIXED)

        - cv.IMWRITE_PNG_BILEVEL: 0/1 [0-normal; 1-black and white]

    - webP parameter:

        - cv.IMWRITE_WEBP_QUALITY: 0-100

    - tiff parameter:

        - cv.IMWRITE_TIFF_COMPRESSION: 1-7
        
        - cv.IMWRITE_TIFF_RESUNIT: 1/2/3 [1- no unit, 2- inch, 3- cm]
        
        - cv.IMWRITE_TIFF_XDPI: horixzontal dpi
        
        - cv.IMWRITE_TIFF_YDPI: vertical dpi

In [2]:
result = cv.imwrite("FLOWER.jpg",img,params=[cv.IMWRITE_JPEG_QUALITY,90])

if not result:
    print("Could not save image.")

NameError: name 'img' is not defined

#### `.shape`: image dimensions
---

- returns (height, width, color channel)

    - channels:
        
        - 3: BGR [blue, green , red]

        - no value: GrayScale

In [ ]:
h, w, c = img.shape
print(f"Height: {h}\nWidth: {w}\nColor Channel: {c}")

Height: 148
Width: 196
Color Channel: 3


**manual grayscale conversion**

In [ ]:
import numpy as np

b, g, r = cv.split(img)

gray = b*0.114 + g*0.587 + r*0.299
gray = gray.astype(np.uint8)

cv.imshow("black and white",gray)
cv.waitKey(0)
cv.destroyWindow("black and white")

27

`.cvtColor()`:

- image to convert

- code:

    - cv.COLOR_BGR2GRAY

    - cv.COLOR_BGR2RGB

    - cv.COLOR_BGR2HSV

    - cv.COLOR_BGR2LAB

    - cv.COLOR_GRAY2BGR

In [ ]:
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

rgb = cv.cvtColor(img,cv.COLOR_BGR2RGB)

cv.imshow("GRAY",gray)
cv.imshow("RGB",rgb)

cv.waitKey(0)

cv.destroyWindow("GRAY")
cv.destroyWindow("RGB")

In [ ]:
# ASSIGNMENT: 01

# 1. Take image location as user input
# 2. Ask to show the image
# 3. Ask to save the image, if yes ask tha name of the image

class Image:
    def __init__(self):
        pass
    
    def open(self,loc):
        img = cv.imread(loc)
        return img

    def grayscale(self,imgMat):
        gray = cv.cvtColor(imgMat,cv.COLOR_BGR2GRAY)
        return gray

    def show(self,window,imgMat):
        cv.imshow(window,imgMat)
        cv.waitKey(0)
        cv.destroyWindow(window)

    def save(self,imgMat,saveAs):
        saved = cv.imwrite(saveAs,imgMat)
        return saved
    
img = Image()
path = input("Enter image location: ")
imgMatBGR = img.open(path)
    
if imgMatBGR is None:
    sys.exit()

viewBGR = input("\nDo you want to view the original image ? [y/n]")
if viewBGR.lower() == 'y':
    img.show("Original",imgMatBGR)

imgMatGray = img.grayscale(imgMatBGR)
viewGray = input("\nDo you want to view the GrayScale image ? [y/n]")
if viewGray.lower() == 'y':
    img.show("GrayScale",imgMatGray)

saveImg = input("\nDo you want to save this GrayScale image ? [y/n]")
while saveImg.lower() == 'y':
    name = input("Enter the file name: ").strip()
    if '.' not in name:
        name += ".png"
    saved = img.save(imgMatGray,name)
    if not saved:
        saveImg = input("File not saved, save again ? [y/n]")
    else:
        break

### **Resizing Image**

---
---


#### `.resize()`

> Faster processing, Standardized input size for ML Models 

- src: original image

- dsize: (width, height)

- fx, fy: Scale factors (used instead of dsize) [new_width = old * fx; new_height = old * fy]

- interpolation: method of resizing

| Method        | Use                       |
| ------------- | ------------------------- |
| INTER_AREA    | Chhota karne ke liye best |
| INTER_LINEAR  | Default                   |
| INTER_CUBIC   | High quality (slow)       |
| INTER_NEAREST | Fast but blur/pixelated   |






In [9]:
img = cv.imread("download.jpg")

if img is None:
    print("Image not found.")
else:
    print("Image loaded.")
    h, w = img.shape[:2]
    new_w = 400
    new_h = int((new_w/w) * h)
    resized = cv.resize(img,(new_w,new_h))
    cv.imshow("original",img)
    cv.imshow("resized using dsize",resized)

    resized = cv.resize(img,None,fx=2,fy=2)
    cv.imshow("resized using fx/fy",resized)

    scale = 60
    height = int(h/scale*100)
    width = int(w/scale*100)
    resized = cv.resize(img,(width,height))

    cv.imshow("Scale percentage",resized)

    cv.waitKey(0)
    cv.destroyAllWindows()    



Image loaded.


#### CROPPING : slicing

In [2]:
img = cv.imread("download.jpg")
img = cv.resize(img,None,fx=2,fy=2)
h,w,c = img.shape
print(h,w,c)
print(img)
img = img[100:200,100:300]
cv.imshow("cropped",img)
cv.waitKey()
cv.destroyAllWindows()

296 392 3
[[[63 27 21]
  [63 27 21]
  [63 27 21]
  ...
  [51 23 16]
  [51 23 16]
  [51 23 16]]

 [[63 27 21]
  [63 27 21]
  [63 27 21]
  ...
  [51 23 16]
  [51 23 16]
  [51 23 16]]

 [[63 27 21]
  [63 27 21]
  [63 27 21]
  ...
  [52 24 17]
  [52 24 17]
  [52 24 17]]

 ...

 [[96 98 56]
  [96 98 56]
  [97 99 57]
  ...
  [54 27 17]
  [54 27 17]
  [54 27 17]]

 [[96 98 56]
  [96 98 56]
  [97 99 57]
  ...
  [54 27 17]
  [54 27 17]
  [54 27 17]]

 [[96 98 56]
  [96 98 56]
  [97 99 57]
  ...
  [54 27 17]
  [54 27 17]
  [54 27 17]]]


In [8]:
# getting mid part

h_mid = int(h/2)
w_mid = int(w/2)


height = 70
width = 70

img = cv.imread("download.jpg")
print(img.shape)
img = img[h_mid-height:h_mid+height,w_mid-width:w_mid+width]

cv.imshow("Cropeed",img)
cv.waitKey()
cv.destroyAllWindows()

(148, 196, 3)


`selectROI("message",imgMat)`: used to select a specific area

> returns x, y, width, height

In [15]:
# mouse selection

img = cv.imread("download.jpg")
roi = cv.selectROI("Select area",img)
x, y, w, h = roi

cropped = img[y:y+h,x:x+w]
cv.imshow("Cropped",cropped)
cv.waitKey()
cv.destroyAllWindows()

`getRotationMatrix2D(centre,angle,scale)`

- scale: 0.5- shrink; 1- normal; 2- enlarge

- degree: positive for anticlockwise; negative for clockwise

> returns: [[a,b,tx],[c,d,ty]]


`warpAffine(imgMat,roatedMat,dsize,)`

Original Image

      ↓

Get Rotation Matrix

      ↓

Compute new pixel positions

      ↓

Reverse mapping

      ↓

Interpolation

      ↓

Border filling

      ↓

Final rotated image


In [29]:
img = cv.imread("download.jpg")

if img is not None:
    h, w = img.shape[:2]

    # step 1
    matrix = cv.getRotationMatrix2D((h//2,w//2),-45,1)

    print(matrix)
    # step 2
    rotated = cv.warpAffine(img,matrix,(w,h))
    cv.imshow("Rotated",rotated)
    cv.waitKey()
    cv.destroyAllWindows()



[[  0.70710678  -0.70710678  90.97056275]
 [  0.70710678   0.70710678 -23.62236636]]
